import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import GuestNavbar from "@/components/layout/customer/Navbar";
import SessionProvider from "@/components/providers/SessionProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="flex flex-col min-h-screen bg-slate-50 text-slate-900 antialiased">
        <SessionProvider>
          <GuestNavbar />
          <main className="flex-1 flex flex-col w-full">
            {children}
          </main>
          <Toaster richColors closeButton position="top-center" />
          <footer className="w-full border-t border-slate-200 bg-white py-6 text-center">
            <nav className="mb-2 flex justify-center gap-4 text-sm font-medium text-slate-500">
              <Link href="/login" className="hover:text-black-600 transition-colors">Login</Link>
              <span className="text-slate-300">|</span>
              <Link href="/signup" className="hover:text-black-600 transition-colors">Sign Up</Link>
            </nav>
            <p className="text-xs text-slate-400">© 2026 My App. All rights reserved.</p>
          </footer>
        </SessionProvider>
      </body>
    </html>
  );
}
